spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${env.OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${env.OAUTH2_GOOGLE_CLIENT_SECRET}